Revert "Servo: V3: Allow for non-FTDI Interfaces"
This change causes failures starting servod:
  File "/home/chromeos-test/hdctools/build/servo/ftdi_common.py", line 7, in <module>
    import servo_interfaces
ImportError: No module named servo_interfaces

This reverts commit d0481c562184168c086c08fcf9b91606b5a4c627

Change-Id: I5f2abb459f87727c06dc70492555903fc8feca47
Reviewed-on: https://gerrit.chromium.org/gerrit/45364
Commit-Queue: Richard Barnette <jrbarnette@chromium.org>
Tested-by: Richard Barnette <jrbarnette@chromium.org>
Reviewed-by: Todd Broch <tbroch@chromium.org>