HDCTOOLS: Add useful utility macros
Details

   assert_on_compile() macro enables assertions which can be evaluated
   completely at compile-time to cause no additional code to be
   emitted for the program.

   This assertion system will fail is the cannot be evaluated at
   compile time, and if the expression is not true.

   If the expression cannot be evaluated at runtime, the following
   error will be generated:

     assert_on_compile(printf(""));
     error: enumerator value for ‘assert_on_compile_enum’ is not an integer constant

  If the expression is a compile-time constant, and it fails, the
  following error will be produced:

     assert_on_compile(0);
     error: size of array ‘assert_on_compile_type’ is negative

  ARRAY_LENGTH() produces the number of elements in an array type.

  PARSE_NUMBER uses strtoul() to parse numbers, and ensures that the
  parsed number fits in the destination without changing the value.

  MAKE_BYTE creates a properly-typed byte from two nibbles.

Testing

  Ensured macros work, as shown above.  The macros are not yet used.

BUG=none
TEST=See above.

Change-Id: Ia012e1fd7fc0ec603eeb75d64698f21119365016
Signed-off-by: Taylor Hutt <thutt@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/11527