[hdctools]  Allow tidy to make INA generated files pretty
On the outside chance humans look at these xml files its nicer if tidy
is run without the -errors flag so that its allow to modify the file.

Also w/o it following error is exposed in pythons xml parser
  xml.parsers.expat.ExpatError: not well-formed (invalid token): line
  10, column 43

Although I can't find anything wrong with the source xml

BUG=none
TEST=manual,
1. emerge hdctools
2. sudo servod -c servo.xml -c servo_loc.xml ...

Change-Id: Ic3a0719dca7cf80dbeb1f8712db6e25672557ef6
Reviewed-on: https://gerrit.chromium.org/gerrit/11498
Reviewed-by: Taylor Hutt <thutt@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>