bbmux_controller: change the check for omax muxing
When upgrading to the 3.14 kernel on beaglebone_servo, with CONFIG_OMAP_MUX=y
the directory /sys/kernel/debugging/omap_mux is created even if no pins are
muxed directly from kernel code in arc/arm/mach-*. Because of that servod fails
to start and gives a long trace that ends with the line:
IOError: [Errno 13] Permission denied: '/sys/kernel/debug/omap_mux/lcd_data8'

To fix the issue, check if there are actually any muxfiles in omap_mux
directory.

BUG=none
TEST=servod successfully starts on kernel 3.14 and on kernel 3.8

Change-Id: If6b22947521c97d5f51d7b053e6391540be979c7
Reviewed-on: https://chromium-review.googlesource.com/328504
Commit-Ready: Victor Dodon <printesoi@chromium.org>
Tested-by: Victor Dodon <printesoi@chromium.org>
Reviewed-by: Todd Broch <tbroch@chromium.org>