Fix runtime exception 'No module named fdpexpect'
pexpect 3.0 moved package fdexpect into pexpect
http://pexpect.readthedocs.org/en/stable/history.html#version-3-0

This causes runtime error at systems with recent pexpect (e.g. Arch)

$ sudo servod -b daisy
Traceback (most recent call last):
  File "/usr/bin/servod", line 9, in <module>
    load_entry_point('servo===0.0.1-1fab631', 'console_scripts', 'servod')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2709, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2369, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2375, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/servo/servod.py", line 20, in <module>
    import servo_server
  File "/usr/lib/python2.7/site-packages/servo/servo_server.py", line 17, in <module>
    from drv.hw_driver import HwDriverError
  File "/usr/lib/python2.7/site-packages/servo/drv/__init__.py", line 11, in <module>
    import arm_ec
  File "/usr/lib/python2.7/site-packages/servo/drv/arm_ec.py", line 8, in <module>
    import ec
  File "/usr/lib/python2.7/site-packages/servo/drv/ec.py", line 17, in <module>
    import pty_driver
  File "/usr/lib/python2.7/site-packages/servo/drv/pty_driver.py", line 7, in <module>
    import fdpexpect
ImportError: No module named fdpexpect

BRANCH=none
BUG=none
TEST=sudo servod -b daisy

Change-Id: I39902b512678330002dbe4d98b16062d69a96316
Signed-off-by: Anatol Pomazau <anatol@google.com>
Reviewed-on: https://chromium-review.googlesource.com/323202
Reviewed-by: Todd Broch <tbroch@chromium.org>