servo: fix a log format when handling urllib exception
urrlib.retrieve can throw IOError if for example the hostname lookup
fails or the connection is refused, but in these cases the errno field
is a string and not an integer, leading to another exception:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
      msg = self.format(record)
    File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
      return fmt.format(record)
    File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
      record.message = record.getMessage()
    File "/usr/lib/python2.7/logging/__init__.py", line 335, in
  getMessage
      msg = msg % self.args
  TypeError: %d format: a number is required, not str
  Logged from file servo_server.py, line 629
instead of logging the caught IOError. Now the output is as expected:
  Servod - ERROR - servo_server.py:631:download_image_to_usb - Failed
  to transfer image to USB device: [Errno -2] Name or service not known
  ( socket error )

BUG=None
TEST=`test_that --board=$BOARD --args "servo_host=$SERVO_HOST \
     servo_port=9999 \
     image='http://non-existent:8080/static/$BOARD/$BUILD/chromiumos_test_image.bin'" \
     $DUT platform_InstallTestImage` and check that servod.log contains
     the corrent output

Change-Id: I80edb2b9a3ba1f2926e04bba19d93a74ffcf274e
Reviewed-on: https://chromium-review.googlesource.com/341331
Commit-Ready: Victor Dodon <printesoi@chromium.org>
Tested-by: Victor Dodon <printesoi@chromium.org>
Reviewed-by: Nick Sanders <nsanders@chromium.org>
Reviewed-by: Dan Shi <dshi@google.com>